[I 15:24:32.948 NotebookApp] Serving notebooks from local directory: /home/users/zg78/adver_ml
[I 15:24:32.949 NotebookApp] Jupyter Notebook 6.4.3 is running at:
[I 15:24:32.949 NotebookApp] http://linux31:8881/?token=4bb0afbb0c6549c80c68fec1fbd89184bc73d23bec657df2
[I 15:24:32.949 NotebookApp]  or http://127.0.0.1:8881/?token=4bb0afbb0c6549c80c68fec1fbd89184bc73d23bec657df2
[I 15:24:32.949 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 15:24:32.957 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///home/users/zg78/.local/share/jupyter/runtime/nbserver-36777-open.html
    Or copy and paste one of these URLs:
        http://linux31:8881/?token=4bb0afbb0c6549c80c68fec1fbd89184bc73d23bec657df2
     or http://127.0.0.1:8881/?token=4bb0afbb0c6549c80c68fec1fbd89184bc73d23bec657df2
[I 15:25:25.712 NotebookApp] 302 GET / (152.3.140.46) 1.480000ms
/home/users/zg78/_conda/envs/concept/lib/python3.6/json/encoder.py:257: UserWarning: date_default is deprecated since jupyter_client 7.0.0. Use jupyter_client.jsonutil.json_default.
  return _iterencode(o, 0)
[W 15:25:44.176 NotebookApp] Notebook data/npz2npy.ipynb is not trusted
/home/users/zg78/_conda/envs/concept/lib/python3.6/json/encoder.py:257: UserWarning: date_default is deprecated since jupyter_client 7.0.0. Use jupyter_client.jsonutil.json_default.
  return _iterencode(o, 0)
[I 15:25:44.349 NotebookApp] Kernel started: 4667a8f1-c0d0-445a-affb-b3e3c74dd9bc, name: python3
ERROR:asyncio:Exception in callback <TaskStepMethWrapper object at 0x7fbbe5b3ed30>()
handle: <Handle <TaskStepMethWrapper object at 0x7fbbe5b3ed30>()>
Traceback (most recent call last):
  File "/home/users/zg78/_conda/envs/concept/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
KeyError: <_UnixSelectorEventLoop running=True closed=False debug=False>
[I 15:27:44.349 NotebookApp] Saving file at /data/npz2npy.ipynb
[W 15:27:44.350 NotebookApp] Notebook data/npz2npy.ipynb is not trusted
[I 15:29:44.344 NotebookApp] Saving file at /data/npz2npy.ipynb
[W 15:29:44.344 NotebookApp] Notebook data/npz2npy.ipynb is not trusted
[I 15:31:45.091 NotebookApp] Saving file at /data/npz2npy.ipynb
[W 15:31:45.093 NotebookApp] Notebook data/npz2npy.ipynb is not trusted
[I 15:33:45.084 NotebookApp] Saving file at /data/npz2npy.ipynb
[W 15:33:45.085 NotebookApp] Notebook data/npz2npy.ipynb is not trusted
[I 15:35:44.346 NotebookApp] Saving file at /data/npz2npy.ipynb
[W 15:35:44.347 NotebookApp] Notebook data/npz2npy.ipynb is not trusted
[I 15:37:44.323 NotebookApp] Saving file at /data/npz2npy.ipynb
[W 15:37:44.323 NotebookApp] Notebook data/npz2npy.ipynb is not trusted
[I 15:39:44.345 NotebookApp] Saving file at /data/npz2npy.ipynb
[W 15:39:44.346 NotebookApp] Notebook data/npz2npy.ipynb is not trusted
[I 15:41:44.330 NotebookApp] Saving file at /data/npz2npy.ipynb
[W 15:41:44.331 NotebookApp] Notebook data/npz2npy.ipynb is not trusted
[I 15:43:44.362 NotebookApp] Saving file at /data/npz2npy.ipynb
[W 15:43:44.363 NotebookApp] Notebook data/npz2npy.ipynb is not trusted
[I 15:45:44.205 NotebookApp] Starting buffering for 4667a8f1-c0d0-445a-affb-b3e3c74dd9bc:4d724ffe79b14fdd8aaf37eb5e658672
[I 15:45:44.339 NotebookApp] Saving file at /data/npz2npy.ipynb
[W 15:45:44.340 NotebookApp] Notebook data/npz2npy.ipynb is not trusted
[I 15:45:52.974 NotebookApp] Kernel restarted: 4667a8f1-c0d0-445a-affb-b3e3c74dd9bc
[I 15:45:53.060 NotebookApp] Restoring connection for 4667a8f1-c0d0-445a-affb-b3e3c74dd9bc:4d724ffe79b14fdd8aaf37eb5e658672
[I 15:47:44.323 NotebookApp] Saving file at /data/npz2npy.ipynb
[W 15:47:44.324 NotebookApp] Notebook data/npz2npy.ipynb is not trusted
[I 15:47:58.541 NotebookApp] Starting buffering for 4667a8f1-c0d0-445a-affb-b3e3c74dd9bc:4d724ffe79b14fdd8aaf37eb5e658672
[I 15:47:58.988 NotebookApp] Kernel restarted: 4667a8f1-c0d0-445a-affb-b3e3c74dd9bc
[I 15:47:59.077 NotebookApp] Restoring connection for 4667a8f1-c0d0-445a-affb-b3e3c74dd9bc:4d724ffe79b14fdd8aaf37eb5e658672
[I 15:47:59.899 NotebookApp] Replaying 3 buffered messages
[I 15:49:05.187 NotebookApp] Saving file at /data/npz2npy.ipynb
[W 15:49:05.188 NotebookApp] Notebook data/npz2npy.ipynb is not trusted
[I 15:49:05.363 NotebookApp] Saving file at /data/npz2npy.ipynb
[W 15:49:05.364 NotebookApp] Notebook data/npz2npy.ipynb is not trusted
[I 16:01:44.322 NotebookApp] Saving file at /data/npz2npy.ipynb
[W 16:01:44.323 NotebookApp] Notebook data/npz2npy.ipynb is not trusted
[I 16:02:39.399 NotebookApp] Starting buffering for 4667a8f1-c0d0-445a-affb-b3e3c74dd9bc:4d724ffe79b14fdd8aaf37eb5e658672
[I 16:02:39.944 NotebookApp] Kernel restarted: 4667a8f1-c0d0-445a-affb-b3e3c74dd9bc
[I 16:02:39.969 NotebookApp] Restoring connection for 4667a8f1-c0d0-445a-affb-b3e3c74dd9bc:4d724ffe79b14fdd8aaf37eb5e658672
[I 16:02:40.843 NotebookApp] Replaying 3 buffered messages
[I 16:02:49.043 NotebookApp] Kernel interrupted: 4667a8f1-c0d0-445a-affb-b3e3c74dd9bc
[I 16:02:49.180 NotebookApp] Kernel interrupted: 4667a8f1-c0d0-445a-affb-b3e3c74dd9bc
[I 16:02:49.355 NotebookApp] Kernel interrupted: 4667a8f1-c0d0-445a-affb-b3e3c74dd9bc
[I 16:03:16.238 NotebookApp] Kernel interrupted: 4667a8f1-c0d0-445a-affb-b3e3c74dd9bc
[I 16:03:16.432 NotebookApp] Kernel interrupted: 4667a8f1-c0d0-445a-affb-b3e3c74dd9bc
[I 16:03:44.377 NotebookApp] Saving file at /data/npz2npy.ipynb
[I 16:05:44.336 NotebookApp] Saving file at /data/npz2npy.ipynb
[I 16:07:44.359 NotebookApp] Saving file at /data/npz2npy.ipynb
[I 16:09:39.743 NotebookApp] New terminal with automatic name: 1
[I 16:09:45.075 NotebookApp] Saving file at /data/npz2npy.ipynb
[I 16:26:27.141 NotebookApp] Saving file at /data/npz2npy.ipynb
[I 16:27:44.311 NotebookApp] Saving file at /data/npz2npy.ipynb
[I 16:29:45.085 NotebookApp] Saving file at /data/npz2npy.ipynb
